### PR TITLE
Various improvements to tests and compatibility

### PR DESCRIPTION
**Pull request by dcramer**
- Switch to pytest
- Add flake8
- Enhance TravisCI configuration
  - Switch to container builds
  - Add pypy to grid
  - Add explicit mysql/postgres/sqlite to grid
  - Add development Django to grid
- Raise Django requirement to 1.4+

[Review on Reviewable](https://reviewable.io/reviews/disqus/django-bitfield/59)

### CODE REVIEW

**Comment by dcramer** [comment]
I will land this as soon as Travis is green. And as soon as that happens I'll push out a new version.

**Comment by dcramer** [comment]
It looks like we've got some issues with MySQL here. I'm not entirely sure what our support was before, but the new changes for 1.8 compatibility definitely break it.

**Comment by adepue** [comment]
From looking at the test BitFieldTest.test_update,  the issue here is that mysql and postgres interpret the following statement differently:

```sql
UPDATE `tests_bitfieldtestmodel` SET `another_name` = `tests_bitfieldtestmodel`.`another_name` | -2 WHERE `tests_bitfieldtestmodel`.`id` = 8 
```

In postgres the result is 14 (like expected), but in mysql, the resulting value is 9223372036854775807.  This is due to an out-of-range error that just sets the column to the max int.

Still looking into a fix, but I dont see any way this could have worked in the past either.

**Comment by dcramer** [comment]
@adepue it def never worked on MySQL base don my recollection. If you guys are using it we can probably put some collective effort into fixing it, or disabling the behavior/test for MySQL.

(Also totally forgot I had even put up this PR, probably should just land this)

**Comment by adepue** [comment]
Yeah we are using it and have been for a while.  It is really just the negating behavior that doesn't work.  I am happy to spend some time on it to help.
Even if just exempt that failing test from mysql for now, and then fix in . release, we are no worse off I dont think.

**Comment by dcramer** [comment]
@adepue yeah I think i'd be content just asserting not mysql (if we can) when you apply negation since the consequences can be fairly severe

**Comment by adepue** [comment]
Yeah that would work... except the negation appears to be done in python before building the query.
We could assert if the either side of the bitand/bitor is negative?

**Comment by adepue** [comment]
Let me try to get a PR together for that assertion block... Will likely be in the morning.

**Comment by adepue** [comment]
@dcramer I am not sure on an easy way to only assert when you decide to bitand/or with a negated value.  I think (?) we want to allow saving of negative values... it is really just the bit wise operations at the DB site that are the issue.
Looking at BitQueryLookupWrapper may be a good spot, but that seems targetted at a specific bit and not the result of the entire field.

How bad (possibly very) is it to exempt these failing tests under mysql and put a huge note/word of caution in the README?  Just to get the latest release out and we can figure out another dot release with a better assertion fix? 
In the short term I dont think we are any worse off than we ever have been... adding some documentation improves the situation at least.

**Comment by dcramer** [comment]
Probably ok to mark as broken in mysql.

I do think its possible to hook negation but I'm not 100% sure off hand. I'll take a look tomorrow.

**Comment by dcramer** [comment]
It seems basically all query operations fail in MySQL.

We could put a giant "nothing works in mysql" banner, or simply dont claim it as supported

**Comment by adepue** [comment]
Sounds good to me.  Our use case is really just the flags part on the python side... we dont issue any bitwise operations into mysql.

Thanks

**Pull request merged**
