### PR TITLE
types.py: alias for psycopg2 removed with Django 3.0

### PR DESCRIPTION
**Pull request by rystan**
Django 3.0 dropped alias for postgresql_psycopg2 -> postgresql

### CODE REVIEW

**Comment by rystan** [comment]
Fixes issue #96

**Comment by timabbott** [comment]
This seems to fail CI; can you investigate?  Looks like `django` isn't imported directly there.

**Comment by rystan** [comment]
Sorry, I copy and pasted from an older local version of the file that still had 'import django' at the top.

**Comment by apinsard** [comment]
Thanks, gonna use your patch until it gets released. :)

However, is it really necessary to write explicit code to support Django <= 1.9 which official extended supported ended in April 2018?

**Comment by timabbott** [comment]
We removed support for Django below 1.11; so this should be updated to reflect that.  

@mateuszmandera if you get some time, it'd be great to fix and then we can do a quick release with Django 3.x support as well.

**Comment by mateuszmandera** [comment]
@timabbott Adjusted in https://github.com/disqus/django-bitfield/pull/100

**Comment by timabbott** [comment]
@rystan can you rebase now that #100 is merged?

**Comment by mateuszmandera** [comment]
@timabbott I think this can just be closed, #100 was a fixed version of this PR.

**Pull request closed without merging**
