### PR TITLE
Django 1.8 Compatibility

### PR DESCRIPTION
**Pull request by SeanHayes**
Depends on PR #55.

The tests suite now runs against Django 1.7 and 1.8, and passes for all versions.

### CODE REVIEW

**Comment by RobertoMaurizzi** [comment]
Any news on this? Or should I think about finding another solution for bitfield-like functionality in Django 1.7+?

**Comment by ALenfant** [comment]
I'd also be interested by this PR, I've been trying to update to Django 1.8 and django-bitfield is one of the dependencies preventing me to do so.

**Comment by dcramer** [comment]
Thanks!

**Comment by dcramer** [comment]
It looks like we've got some issues with MySQL here. I'm not entirely sure what our support was before, but this definitely breaks it.

**Comment by SeanHayes** [comment]
@dcramer Is that only MySQL + Django 1.8, or previous versions of Django as well?

**Pull request merged**
