### PR TITLE
Fixed an error where BitQueryLookupWrapper includes an unprocessed rhs value

### PR DESCRIPTION
**Pull request by iamahuman**
..and added some partial race-condition fix to an unused code.
The commit https://github.com/disqus/django-bitfield/commit/8b8aade8d617906d80f0c188fb7647b748eace5f seems to fix the issue disqus#64.

### CODE REVIEW

**Comment by onrik** [comment]
+1

**Comment by iamahuman** [comment]
@onrik Wow, this thread hasn't been dead *yet?*

**Comment by onrik** [comment]
I hope :)

**Comment by tejasjadhav** [comment]
Why isn't this PR accepted yet?

**Comment by iamahuman** [comment]
Neither do other PRs. I'm assuming this project has been abandoned long
since.

**Comment by timabbott** [comment]
@iamahuman I'm now helping with maintenance for this repository, since we use it in Zulip, and it seems like a lot

Can you (1) add some tests for this PR and (2) explain why the changes are correct (ideally in the commit messages)?  It's totally unclear to me what the reasoning is behind these changes.

**Comment by iamahuman** [comment]
@timabbott I'm not sure it's still relevant for the current Django version since it's been almost 3 years. I'll check whether this is still valid later. BTW the XOR part isn't actually needed as part of the PR (but I don't see a problem on that change).

**Comment by iamahuman** [comment]
I now see that the problem actually resides in `bitfield/admin.py`, not `bitfield/query.py` (uses `bitor(F(p), v)` as filter value which certainly isn't how the BitQueryLookupWrapper is designed to be used. I'm still not sure how to fix these since the filter uses an internal API, so...

**Comment by iamahuman** [comment]
Closing this for now since this isn't the most ideal way to patch this (and may even have unexpected semantics).

**Pull request closed without merging**
